---
development:
  APP_URL: http://localhost:4000/
  API_URL: http://localhost:9292/
  API_VERSION: 'v0.1'
test:
  APP_URL: http://localhost:4000/
  API_URL: http://localhost:9292/
  API_VERSION: 'v0.1'
production:
  APP_URL: http://localhost:4000/
  API_URL: http://localhost:9292/
  API_VERSION: 'v0.1'
