---
development:
  APP_URL: http://localhost:4000/
  api_domain: http://localhost:9292/
  api_version: 'v0.1'
test:
  APP_URL: http://localhost:4000/
  api_domain: http://localhost:9292/
  api_version: 'v0.1'
production:
  api_domain: http://localhost:9292/
  api_version: 'v0.1'
