---
development:
  api_domain: http://localhost:9292/
  api_version: 'v0.1'
test:
  api_domain: http://localhost:9292/
  api_version: 'v0.1'
production:
  api_domain: http://localhost:9292/
  api_version: 'v0.1'
